name: mezet
description: "A home screen widget service using MapleStory OPEN API"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  http: ^1.4.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  home_widget: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/config/.env
